export const ActionTypes = {
  CREATE_FOLDER: "CREATE_FOLDER",
  RENAME_FOLDER: "RENAME_FOLDER",
  DELETE_FOLDER: "DELETE_FOLDER",
  CREATE_FILE: "CREATE_FILE",
  DELETE_FILE: "DELETE_FILE",
  RENAME_FILE: "RENAME_FILE",
  SET_SELECTED_NODE: "SET_SELECTED_NODE",
};
